### ISSUE TITLE
Error: Unable to derive master keys for prod / Couldn't set master_key_00

### ISSUE THREAD

**Issue by ClementNerma** [CaramelDunes/prodinfo_gen#29]
Hi, when I try to generate the PRODINFO from donor or from scratch, I get the following error:

```
Dumping keys...
Unable to derive master keys for prod.
Master keys... done in 1869 us
Keygen part done in 2545 us

Couldn't set master_key_00

Done in 4136 us
```

Do you know why this happens and how to solve this problem?

I'm using a Switch Lite with an SX Lite chip (if this helps).

**Comment by CaramelDunes** [comment]
Hello @ClementNerma, that's definitely odd.
- Does lockpick_rcm work on your console?
- Could you confirm that the master key 00 you are getting from lockpick_rcm is correct? (you can search for it on the internet, or you can email me with your keys so that I double-check them).
- Is this a retail or dev unit?

**Comment by ClementNerma** [comment]
It's been a while but I recall using another method given this one wasn't working. IIRC i used lockpick as a part of the process and got all keys dumped, and used a donor NAND to flash my Switch (which is a retail Lite unit).

**Comment by CaramelDunes** [comment]
Glad you got it to work, maybe you used something similar to https://github.com/PabloZaiden/deviceid-exosphere-builder.
